// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroVentas.Api.Data;

#nullable disable

namespace RegistroVentas.Api.Migrations
{
    [DbContext(typeof(RegistroDbContext))]
    partial class RegistroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("RegistroVentas.Api.Data.RegistroOperacion", b =>
                {
                    b.Property<int>("Pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasColumnType("NUMERIC");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Secreto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Pk");

                    b.HasIndex("Referencia")
                        .IsUnique();

                    b.ToTable("RegistrosOperaciones", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
